version: '3'
services:
  api:
    build: .
    command: yarn
    volumes:
      - .:/api/
    ports:
      - '3333:3333'
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://todoapp@postgres/todos
  postgres:
    image: postgres:10.10
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
